%%% created by RB on 23.12.2020

% Fig 7b (10x): Opto-index indivdual data points with average and errorbars - comparison baselines between before and during photostim. 

if totalStim ==6
    
    titleFig7b = {'Opto-index 100% visual stim. +/- photostim. Base2',...
        'Opto-index 100% visual stim. +/- photostim. Base3',...
        'Opto-index 100% visual stim. +/- photostim. Base4',...
        'Opto-index 100% visual stim. +/- photostim. Base5',...
        'Opto-index 100% visual stim. +/- photostim. Base6',...
        'Opto-index 0% visual stim. +/- photostim. Base2',...
        'Opto-index 0% visual stim. +/- photostim. Base3',...
        'Opto-index 0% visual stim. +/- photostim. Base4',...
        'Opto-index 0% visual stim. +/- photostim. Base5',...
        'Opto-index 0% visual stim. +/- photostim. Base6'};
    
    saveFig7b = {'OptoindexScatterplot100Base2.fig', 'OptoindexScatterplot100Base3.fig',...
        'OptoindexScatterplot100Base4.fig', 'OptoindexScatterplot100Base5.fig',...
        'OptoindexScatterplot100Base6.fig',...
        'OptoindexScatterplot0Base2.fig', 'OptoindexScatterplot0Base3.fig',...
        'OptoindexScatterplot0Base4.fig', 'OptoindexScatterplot0Base5.fig',...
        'OptoindexScatterplot0Base6.fig'};
elseif totalStim == 1
    titleFig7b = {'Opto-index 100% visual stim. +/- photostim. Base2',...
    'Opto-index 100% visual stim. +/- photostim. Base3',...
    'Opto-index 50% visual stim. +/- photostim. Base2',...
    'Opto-index 50% visual stim. +/- photostim. Base3',...
    'Opto-index 25% visual stim. +/- photostim. Base2',...
    'Opto-index 25% visual stim. +/- photostim. Base3',...
    'Opto-index 12% visual stim. +/- photostim. Base2',...
    'Opto-index 12% visual stim. +/- photostim. Base3',...
    'Opto-index 0% visual stim. +/- photostim. Base2',...
    'Opto-index 0% visual stim. +/- photostim. Base3'};

saveFig7b = {'OptoindexScatterplot100Base2.fig', 'OptoindexScatterplot100Base3.fig',...
    'OptoindexScatterplot50Base2.fig', 'OptoindexScatterplot50Base3.fig',...
    'OptoindexScatterplot25Base2.fig', 'OptoindexScatterplot25Base3.fig',...
    'OptoindexScatterplot12Base2.fig', 'OptoindexScatterplot20Base3.fig',...
    'OptoindexScatterplot0Base2.fig', 'OptoindexScatterplot0Base3.fig'};
end

for cond = (1:2:totalConds)
    for stim =2:numel(baseStim)
        figure
        ax = gca;
        hold on            
        for unit = 1:totalUnits
            plot(1, OIndexAllStimBase((cond+1)/2,unit, stim), 'Marker','o','MarkerSize',20,'Color', C_units(unit,:));
        end
        scatter((1.1), meanOIndexAllStimBase((cond+1)/2, stim), 200, '+', 'k', 'LineWidth', 2); hold on
        
        ylabel('Opto-index','FontSize',24);
        % set(b,'facecolor',[1 1 1]);
        set(ax,'XLim',[0.8 1.2],'YLim', [-1 1],'FontSize',24);
        title(titleFig7b{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))},'FontSize',18);
        background = get(gcf, 'color');
        set(gcf,'color','white'); hold on
        set(gca,'FontSize',24, 'XTickLabel',{'Without photostim.','With photostim.'},'XTick',[1 2]);
        errorbar((1.1),meanOIndexAllStimBase((cond+1)/2, stim),STEMOIndexAllStimBase((cond+1)/2, stim),'.k','LineWidth',2);
        box off
        if saveFigs == true
            savefig(strcat(savePath, saveFig7b{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))}));
        end
    end
end