%%% created by RB on 20.01.2021

% Fig. 7e -  histograms of opto-index for each cell type

if totalStim == 6
    titleFig7e = {'Histogram OI 100% visual stim. +/- photostim. Base2',...
        'Histogram OI 100% visual stim. +/- photostim. Base3',...
        'Histogram OI 100% visual stim. +/- photostim. Base4',...
        'Histogram OI 100% visual stim. +/- photostim. Base5',...
        'Histogram OI 100% visual stim. +/- photostim. Base6',...
        'Histogram OI 0% visual stim. +/- photostim. Base2',...
        'Histogram OI 0% visual stim. +/- photostim. Base3',...
        'Histogram OI 0% visual stim. +/- photostim. Base4',...
        'Histogram OI 0% visual stim. +/- photostim. Base5',...
        'Histogram OI 0% visual stim. +/- photostim. Base6'};
    
    saveFig7e = {'HistOI100Base2.fig', 'HistOI100Base3.fig',...
        'HistOI100Base4.fig', 'HistOI100Base5.fig',...
        'HistOI100Base6.fig',...
        'HistOI0Base2.fig', 'HistOI0Base3.fig',...
        'HistOI0Base4.fig', 'HistOI0Base5.fig',...
        'HistOI0Base6.fig'};
elseif totalStim == 1
    titleFig7e = {'Histogram OI 100% visual stim. +/- photostim. Base2',...
        'Histogram OI 100% visual stim. +/- photostim. Base3',...
        'Histogram OI 50% visual stim. +/- photostim. Base2',...
        'Histogram OI 50% visual stim. +/- photostim. Base3',...
        'Histogram OI 25% visual stim. +/- photostim. Base2',...
        'Histogram OI 25% visual stim. +/- photostim. Base3',...
        'Histogram OI 12% visual stim. +/- photostim. Base2',...
        'Histogram OI 12% visual stim. +/- photostim. Base3',...
        'Histogram OI 0% visual stim. +/- photostim. Base2',...
        'Histogram OI 0% visual stim. +/- photostim. Base3'};
    
    saveFig7e = {'HistOI100Base2.fig', 'HistOI100Base3.fig',...
        'HistOI50Base2.fig', 'HistOI50Base3.fig',...
        'HistOI25Base2.fig', 'HistOI25Base3.fig',...
        'HistOI12Base2.fig', 'HistOI20Base3.fig',...
        'HistOI0Base2.fig', 'HistOI0Base3.fig'};
end

for cond = (1:2:totalConds)
    for stim = 2:numel(baseStim)
        excUnits = iUnitsFilt &  classUnitsAll == 1;
        inhUnits = iUnitsFilt &  classUnitsAll == 2;
        binEdges = 0.25;
        edges = [-1:binEdges:1];
        
%         figure
%         histogram(OIndexAllStimBase((cond+1)/2,excUnits, stim), edges, 'FaceColor', [1 1 1], 'EdgeColor', [0 1 0]);hold on
%         histogram(OIndexAllStimBase((cond+1)/2,inhUnits, stim), edges, 'FaceColor', [1 1 1], 'EdgeColor', [1 0 0]);
%         title(titleFig7e{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))},'FontSize',18);
        
        f = figure('Renderer', 'painters', 'Position', [680 558 320 420])     
%         f.Position
        [histExc] = histcounts(OIndexAllStimBase((cond+1)/2,excUnits, stim),edges);
        [histInh] = histcounts(OIndexAllStimBase((cond+1)/2,inhUnits, stim),edges);
        normHistExc = histExc/sum(histExc)*100;
        normHistInh = histInh/sum(histInh)*100;
        
        plot(edges(1:end-1)+(edges(2)-edges(1))/2, normHistExc, '.-g'); hold on
        plot(edges(1:end-1)+(edges(2)-edges(1))/2, normHistInh, '.-r')
        xlabel('Opto-index');
%         ylabel('Unit count');  
        ylabel('% unit count'); 
        ax = gca;
        set(ax, 'FontSize',fs);
        set(ax, 'TickDir', 'out');
        set(ax,'FontSize',fs)
        xticks([-1:2*binEdges:1]);
        background = get(gcf, 'color');
        grid on
        grid minor
        box off
        view([90 -90])
        title(titleFig7e{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))},'FontSize',18);
        if saveFigs == true
            savefig(strcat(savePath, saveFig7e{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))}));
        end

    end
end
