%%% created by RB on 23.12.2020

% Fig. 7a - opto-index bar plot with p value for baselines (10x)

if totalStim == 6
    titleFig7a = {'Opto-index 100% visual stim. +/- photostim. Base2',...
        'Opto-index 100% visual stim. +/- photostim. Base3',...
        'Opto-index 100% visual stim. +/- photostim. Base4',...
        'Opto-index 100% visual stim. +/- photostim. Base5',...
        'Opto-index 100% visual stim. +/- photostim. Base6',...
        'Opto-index 0% visual stim. +/- photostim. Base2',...
        'Opto-index 0% visual stim. +/- photostim. Base3',...
        'Opto-index 0% visual stim. +/- photostim. Base4',...
        'Opto-index 0% visual stim. +/- photostim. Base5',...
        'Opto-index 0% visual stim. +/- photostim. Base6'};
    
    saveFig7a = {'OptoindexBarplot100Base2.fig', 'OptoindexBarplot100Base3.fig',...
        'OptoindexBarplot100Base4.fig', 'OptoindexBarplot100Base5.fig',...
        'OptoindexBarplot100Base6.fig',...
        'OptoindexBarplot0Base2.fig', 'OptoindexBarplot0Base3.fig',...
        'OptoindexBarplot0Base4.fig', 'OptoindexBarplot0Base5.fig',...
        'OptoindexBarplot0Base6.fig'};
elseif totalStim == 1
    titleFig7a = {'Opto-index 100% visual stim. +/- photostim. Base2',...
        'Opto-index 100% visual stim. +/- photostim. Base3',...
        'Opto-index 50% visual stim. +/- photostim. Base2',...
        'Opto-index 50% visual stim. +/- photostim. Base3',...
        'Opto-index 25% visual stim. +/- photostim. Base2',...
        'Opto-index 25% visual stim. +/- photostim. Base3',...
        'Opto-index 12% visual stim. +/- photostim. Base2',...
        'Opto-index 12% visual stim. +/- photostim. Base3',...
        'Opto-index 0% visual stim. +/- photostim. Base2',...
        'Opto-index 0% visual stim. +/- photostim. Base3'};
    
    saveFig7a = {'OptoindexBarplot100Base2.fig', 'OptoindexBarplot100Base3.fig',...
        'OptoindexBarplot50Base2.fig', 'OptoindexBarplot50Base3.fig',...
        'OptoindexBarplot25Base2.fig', 'OptoindexBarplot25Base3.fig',...
        'OptoindexBarplot12Base2.fig', 'OptoindexBarplot20Base3.fig',...
        'OptoindexBarplot0Base2.fig', 'OptoindexBarplot0Base3.fig'};
end

for cond = (1:2:totalConds)
    for stim = 2:numel(baseStim)
        figure
        ax = gca;
        hold on
        b = bar((1:totalUnits),sortOIndexAllStimBase((cond+1)/2,:, stim), 'EdgeColor', 'none');
%         b = bar((1:totalUnitsFilt),sortOIndexAllStimBase((cond+1)/2,(1:totalUnitsFilt), stim));
        b.FaceColor = 'flat';
        for unit = (1:totalUnitsFilt)%find(iUnitsFilt)
%             b.CData(unit,:) = C_units(indexOIndexAllStimBase((cond+1)/2,unit, stim),:);
            if classUnitsAll(indexOIndexAllStimBase((cond+1)/2,unit, stim)) == 1
                b.CData(unit,:) = [0 1 0];
            elseif classUnitsAll(indexOIndexAllStimBase((cond+1)/2,unit, stim)) == 2
                b.CData(unit,:) = [1 0 0];
            end    
            y = sortOIndexAllStimBase((cond+1)/2,unit, stim);%
            p_temp = pSuaBaseAll((cond+1)/2,indexOIndexAllStimBase((cond+1)/2,unit, stim), stim);
%             text(unit, y+0.1*sign(y), num2str(pSuaBaseAll((cond+1)/2,indexOIndexAllStimBase((cond+1)/2,unit, stim), stim)),'FontSize',5, 'HorizontalAlignment','center');
%             text(unit, y-0.1*sign(y), [num2str(indexOIndexAllStimBase((cond+1)/2,unit, stim)) ',' num2str(spikeClusterDataAll.goodCodes(indexOIndexAllStimBase((cond+1)/2,unit, stim)))] ,'FontSize',5, 'HorizontalAlignment','center');
            if p_temp <= 0.001
                text(unit, y-0.05*sign(y),'***','FontSize',10, 'HorizontalAlignment','center');
            elseif p_temp <= 0.01
                text(unit, y-0.05*sign(y),'**','FontSize',10, 'HorizontalAlignment','center');
            elseif p_temp <= 0.05
                text(unit, y-0.05*sign(y),'*','FontSize',10, 'HorizontalAlignment','center');
            end
        end
        xlabel('Unit no.');
        ylabel('Opto-index');% (B+ph - B-ph)/(B+ph + B-ph)');
        set(ax,'XLim',[0.5 totalUnitsFilt+0.5],'YLim', [-1 1],'FontSize',fs);
        set(ax, 'TickDir', 'out');
        %     % set(ax,'xtick',[]);
        %     % set(gca, 'XColor', 'w');
        set(ax,'FontSize',fs)
        background = get(gcf, 'color');
        title(titleFig7a{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))},'FontSize',18);
        if saveFigs == true
            savefig(strcat(savePath, saveFig7a{(cond+1)/2*(numel(baseStim)-1)+(stim-numel(baseStim))}));
        end

    end
end
