% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Jan-2022 17:02:57
%  MATLAB version: 9.8.0.1721703 (R2020a) Update 7
% -------------------------------------------------------------------
saveVarsMat = load('bandpass_cheby.mat');

BP = saveVarsMat.BP; % <1x1 dsp.BiquadFilter> unsupported class

clear saveVarsMat;
